FROM node:16-alpine

ENV NODE_ENV development

WORKDIR /usr/app/recipes

COPY ["package.json", "package-lock.json*", "npm-shrinkwrap.json*", ".yarnrc.yml", "yarn*", "./"]

COPY entrypoint.sh /entrypoint.sh

RUN chmod +x /entrypoint.sh

RUN yarn

COPY . .

EXPOSE 5173
EXPOSE 24678

ENTRYPOINT ["/entrypoint.sh"]
